version: "3.7"

services:
  frontend:
    container_name: jump_math_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./scripts/launch_dev.sh:/.dev/launch_dev.sh
      - ./.git/hooks:/.dev/git-hooks
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    entrypoint:
      - /bin/bash
      - /.dev/launch_dev.sh
      - -p
      - /.dev/git-hooks
      - yarn
      - start
  ts-backend:
    container_name: jump_math_ts_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./scripts/launch_dev.sh:/.dev/launch_dev.sh
      - ./.git/hooks:/.dev/git-hooks
      - ./backend:/app
      - /app/node_modules
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    env_file:
      - ./.env
    entrypoint:
      - /bin/bash
      - /.dev/launch_dev.sh
      - -p
      - /.dev/git-hooks
      - yarn
      - dev
