name: "Staging: Deploy backend"

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths:
      - "backend/**"

jobs:
  deploy:
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]"
    if: ${{ github.actor == 'dependabot[bot]' || !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/heroku-deploy
        with:
          email: "${{ secrets.DEV_HEROKU_EMAIL }}"
          apiKey: "${{ secrets.DEV_HEROKU_API_KEY }}"
          appName: "${{ secrets.DEV_PROJECT_ID }}"
          databaseUrl: "${{ secrets.DEV_MG_DATABASE_URL }}"
          firebaseApiKey: "${{ secrets.DEV_FIREBASE_WEB_API_KEY }}"
          firebaseRequestUri: "${{ secrets.DEV_FIREBASE_REQUEST_URI }}"
          firebaseBucket: "${{ secrets.DEV_FIREBASE_STORAGE_DEFAULT_BUCKET }}"
          firebaseProject: "${{ secrets.DEV_PROJECT_ID }}"
          firebasePrivateKey: "${{ secrets.DEV_FIREBASE_SVC_ACCOUNT_PRIVATE_KEY }}"
          firebaseEmail: "${{ secrets.DEV_FIREBASE_SVC_ACCOUNT_CLIENT_EMAIL }}"
          mailerUser: "${{ secrets.DEV_MAILER_USER }}"
          mailerId: "${{ secrets.DEV_MAILER_CLIENT_ID }}"
          mailerSecret: "${{ secrets.DEV_MAILER_CLIENT_SECRET }}"
          mailerRefreshToken: "${{ secrets.DEV_MAILER_REFRESH_TOKEN }}"
          sourceBranch: "staging"
