# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main and development branches
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Unit Tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "backend_lint"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install dependencies for backend
      - name: Install backend dependencies
        run:  yarn --ignore-engines --cwd ./backend/typescript/
        
      # Install dependencies for backend
      - name: Install frontend dependencies
        run:  yarn --ignore-engines --cwd ./frontend/
        
      #Run test for backend
      - name: Run tests for backend
        working-directory: ./backend/typescript
        run: yarn --ignore-engines test
        
      #Run test for backend
      - name: Run tests for frontend
        working-directory: ./frontend
        run: yarn --ignore-engines test
